# permissions for end users to view rhmiconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rhmiconfig-viewer-role
rules:
- apiGroups:
  - rhmiconfig.integreatly.org
  resources:
  - rhmiconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rhmiconfig.integreatly.org
  resources:
  - rhmiconfigs/status
  verbs:
  - get
