---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: integreatly-operator
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
  verbs:
    - "*"
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
- apiGroups:
    - apps
  resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
  verbs:
    - "*"
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
  verbs:
    - get
    - create
- apiGroups:
    - apps
  resourceNames:
    - integreatly-operator
  resources:
    - deployments/finalizers
  verbs:
    - update
- apiGroups:
    - integreatly.org
  resources:
    - "*"
  verbs:
    - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: integreatly-operator
rules:
  - apiGroups:
      - "integreatly.org"
    resources:
      - "*"
    verbs:
      - "*"
  ## Start monitoring
  - apiGroups:
      - "applicationmonitoring.integreatly.org"
    resources:
      - "applicationmonitorings"
      - "blackboxtargets"
    verbs:
      - get
      - create
      - update
      - list
      - delete
  ## End monitoring
  ## Start backup permissions
  - apiGroups:
      - batch
    resources:
      - cronjobs
    verbs:
      - create
      - update
  - apiGroups:
      - "rbac.authorization.k8s.io"
    # these are required so the operator can create a clusterrole to assign to the backup jobs serviceaccount
    # and enable the backup to see the items it needs to backup
    resources:
      - "clusterroles" # may be able to do this with roles instead
      - "clusterrolebindings" # may be able to do this with rolebindings instead
    verbs:
      - create
      - update
      - delete
  # integreatly-operator doesn't require these permissions, but must have them to be able to grant them to the back
  # service accounts it creates and assigns.
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "pods/exec"
    verbs:
      - create
      - update
    ## end backup permissions
  # Start NS reconciliation - This is used to allow the operator to setup the ns needed for each product
  - apiGroups:
      - ""
    resources:
      - namespaces
      - namespaces/finalizers
      - serviceaccounts
      - configmaps
    verbs:
      - list
      - create
      - watch
      - get
      - update
      - delete
  # End NS reconciliation
  # Start subscription creation - This is used to allow the operator to setup catalog source config and remove it if needed.
  # This is used to allow the operator to setup catalog source and remove it if needed.
  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsources
    verbs:
      - create
      - get
      - update
  # This is used to allow the operator to setup catalog source config and remove it if needed.
  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsourceconfigs # required to create catalogsourceconfigs in openshift-marketplace namespace
    verbs:
      - list
      - create
      - watch
      - delete # for uninstallation, these are not cleaned up automatically
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
    verbs:
      - list # needed to get secret for pulling images from default namespace
      - get # needed to get secret for pulling images from default namespace
  - apiGroups:
      - operators.coreos.com
    resources:
      - catalogsourceconfigs/finalizers
    verbs:
      - '*'
  - apiGroups:
      - operators.coreos.com
    resources:
      - operatorgroups
      - subscriptions
      - installplans
    verbs:
      - list
      - create
      - watch
      - get
      - delete
      - update
  # End subscription creation
  - apiGroups:
      - aerogear.org
    resources:
      - keycloaks
      - keycloakrealms
    verbs:
      - list
      - create
      - update
      - watch
      - get
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - apps.3scale.net
    resources:
      - apimanagers
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - org.eclipse.che
    resources:
      - checlusters
      - checlusters/finalizers
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - syndesis.io
    resources:
      - syndesises
      - syndesises/finalizers
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - admin.enmasse.io
    resources:
      - authenticationservices
      - addressplans
      - addressspaceplans
      - brokeredinfraconfigs
      - standardinfraconfigs
      - consoleservices
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - oauth.openshift.io
    resources:
      - oauthclients
    verbs:
      - create
      - get
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - update
      - create
  - apiGroups:
      - apps.openshift.io
    resources:
      - deploymentconfigs/instantiate
      - deploymentconfigs #needed for editing fuse oauth proxy
    verbs:
      - create
      - update #needed for editing fuse oauth proxy
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
  - apiGroups:
      - gpte.opentlc.com
    resources:
      - nexus
    verbs:
      - list
      - create
      - watch
      - get
  - apiGroups:
      - launcher.fabric8.io
    resources:
      - launchers
    verbs:
      - get
      - create
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - "rolebindings"
    verbs:
      - create # needed for creating rolebinding for dedicated-admins to view fuse
      - update # needed for updating subject list to match changes to dedicated-admins users
  # This is used to allow the operator to create and update the rhmi-developers group with users
  - apiGroups:
      - user.openshift.io
    resources:
      - users
    verbs:
      - watch
  - apiGroups:
      - user.openshift.io
    resources:
      - groups
    verbs:
      - get
      - create
      - update
  # rhmi-developers group ends
  - apiGroups:
      - samples.operator.openshift.io
    resources:
      - configs
    verbs:
      - get # needed for updating the samples operator config cr to ignore fuse imagestreams and templates
      - update # needed for updating the samples operator config cr to ignore fuse imagestreams and templates
  # in Opensihft 4.2 some imagestreams are missing required images.
  # Until this is fixed in the product operator, we fix it in the integreatly-operator
  - apiGroups:
      - image.openshift.io
    resources:
      - imagestreams
    verbs:
      - get
      - create
      - delete
      - update
  # end of imagestreams fix permissions
  - apiGroups:
      - template.openshift.io
    resources:
      - templates
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - push.aerogear.org
    resources:
      - unifiedpushservers
    verbs:
      - get
      - create
  # to be removed
  # needed to access db and service crs in the mobile-security-service namespace
  - apiGroups:
      - mobile-security-service.aerogear.org
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - create
  # permissions for the mdc operator
  - apiGroups:
      - mdc.aerogear.org
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - update
      - create
  # remove to here
  # Needed for granting fuse only view
  - apiGroups:
      - build.openshift.io
    resources:
      - jenkins
    verbs:
      - "*"
  # end permissions for granting fuse only view
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheusrules
      - servicemonitors
    verbs:
      - '*'
  - apiGroups:
      - ''
      - project.openshift.io
    resources:
      - projectrequests
    verbs:
      - create