apiVersion: integreatly.org/v1alpha1
kind: Installation
metadata:
  name: integreatly-installation
spec:
  type: workshop
  namespacePrefix: integreatly-
  routingSubdomain: jmonteir.cloudservices.rhmw.io 
  masterUrl: https://console-openshift-console.apps.jmonteir.cloudservices.rhmw.io
  selfSignedCerts: true